// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const autogenDir = path.join(__dirname, "../autogen");

export const fileHeader = `/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the \`pnpm run build:registry\` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

`;
