// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export { default as wormhole } from "./wormhole";
export { default as teritori } from "./teritori";
export { default as stride } from "./stride";
export { default as stargaze } from "./stargaze";
export { default as regen } from "./regen";
export { default as quicksilver } from "./quicksilver";
export { default as osmosis } from "./osmosis";
export { default as osmosistestnet } from "./osmosistestnet";
export { default as noble } from "./noble";
export { default as kujira } from "./kujira";
export { default as kava } from "./kava";
export { default as juno } from "./juno";
export { default as injective } from "./injective";
export { default as gravitybridge } from "./gravitybridge";
export { default as evmos } from "./evmos";
export { default as evmostestnet } from "./evmostestnet";
export { default as evmoslocal } from "./evmoslocal";
export { default as emoney } from "./emoney";
export { default as crescent } from "./crescent";
export { default as cosmoshub } from "./cosmoshub";
export { default as cosmoshublocal } from "./cosmoshublocal";
export { default as comdex } from "./comdex";
export { default as axelar } from "./axelar";