// Copyright Tharsis Labs Ltd.(Evmos)
// SPDX-License-Identifier:ENCL-1.0(https://github.com/evmos/apps/blob/main/LICENSE)

/* eslint-disable */
/**
 * DO NOT MANUALLY EDIT THIS FILE!
 * This file is generated by calling the `pnpm run build:registry` command.
 * 
 * You can find the source code for this script on /scripts/typegen.ts
 */

export default {
  "prefix": "osmo",
  "name": "Osmosis Testnet",
  "cosmosId": "osmo-test-5",
  "identifier": "osmosistestnet",
  "gasPriceStep": {
    "low": "0.005",
    "average": "0.025",
    "high": "0.04"
  },
  "evmId": null,
  "channels": {
    "evmos": {
      "channelId": "channel-1653",
      "counterpartyChannelId": "channel-207"
    }
  },
  "feeToken": "uosmo",
  "cosmosRest": [
    "https://lcd.osmotest5.osmosis.zone"
  ],
  "tendermintRest": null,
  "evmRest": null,
  "cosmosGRPC": null,
  "tokens": [
    {
      "name": "Osmosis",
      "ref": "osmo:OSMO",
      "description": "The native token of Osmosis",
      "symbol": "OSMO",
      "denom": "OSMO",
      "sourcePrefix": "osmo",
      "sourceDenom": "uosmo",
      "minCoinDenom": "uosmo",
      "category": "cosmos",
      "tokenRepresentation": "OSMO",
      "type": "IBC",
      "decimals": 6,
      "erc20Address": "0x3452e23F9c4cC62c70B7ADAd699B264AF3549C19",
      "handledByExternalUI": null,
      "listed": true,
      "coingeckoId": "osmosis"
    }
  ],
  "explorerUrl": "https://testnet.mintscan.io/osmosis-testnet/txs",
  "env": "testnet"
} as const;